name: ci-nodejs-workflow
on: 
    pull_request:
        branches:
            - develop
    push:
        branches:
          - develop
jobs:
    test-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: '14'
            - run: npm install
            - run: npm run test:e2e

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Set up QEMU
              if: success() && github.ref == 'refs/heads/develop'
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              if: success() && github.ref == 'refs/heads/develop'
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              if: success() && github.ref == 'refs/heads/develop'
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build
              if: success() && github.ref == 'refs/heads/develop'
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                context: .
                file: Dockerfile
                push: true
                tags: talessatiro/nodejs-users:latest